TDL-18660 Add retry mechanism and error logging
singer-io/tap-snapchat-ads pull request #14
Opened 2022-04-25 12:32 UTC by karanpanchal-crest

# Description of change
 - Add error logging message for all exception
 - Add unit test to verify that proper message is logged when exception raised

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-05-02 08:45 UTC, savan-chovatiya requested changes

2022-05-02 08:45 UTC, savan-chovatiya commented on tap_snapchat_ads/client.py
> +    },
```suggestion
    406: {
          "raise_exception": SnapchatNotAcceptableError, 
          "message":"You requested a format that isn’t json."
    },
```

2022-05-02 08:45 UTC, savan-chovatiya commented on tap_snapchat_ads/client.py
> +    }}
```suggestion
    }
}
```

2022-05-02 08:45 UTC, savan-chovatiya commented on tap_snapchat_ads/client.py
> +        "message": "Internal Server Error."
```suggestion
        "message": "An error has occurred at Snapchat's end."
```

2022-05-02 08:45 UTC, savan-chovatiya commented on tap_snapchat_ads/client.py
> +        "message": "Service Unavailable."
```suggestion
        "message": "API service is currently unavailable."
```

2022-05-03 07:16 UTC, karanpanchal-crest commented on tap_snapchat_ads/client.py
> +    },
Updated code

2022-05-03 07:17 UTC, karanpanchal-crest commented on tap_snapchat_ads/client.py
> +    }}
Updated code

2022-05-03 07:17 UTC, karanpanchal-crest commented on tap_snapchat_ads/client.py
> +        "message": "Internal Server Error."
Updated message as suggested

2022-05-03 07:17 UTC, karanpanchal-crest commented on tap_snapchat_ads/client.py
> +        "message": "Service Unavailable."
Updated message as suggested

2022-05-04 06:44 UTC, savan-chovatiya approved these changes

2022-05-09 15:54 UTC, KrisPersonal approved these changes

2022-05-09 16:38 UTC, kspeer825 approved these changes

2022-05-10 09:43 UTC, RushT007 approved these changes

2022-05-18 05:34 UTC, merged